### PR TITLE
Fix signal to node conversion in `simulation`

### PR DESCRIPTION
**Pull request by marcelwa**
Lookups in `node_map<SimulationType, Ntk> node_to_value` were made by accessing signals without fetching their respective pointed-to nodes first. This worked fine for the default logic network implementations but fails to work if data types of `signal` and `node` differ or if they cannot be implicitly converted into one another.

This fix addresses the issue by calling `get_node`.

### CODE REVIEW

**Comment by marcelwa** [comment]
I think I've figured out what is going on here. As I've understood now, `node_map` offers a lookup for both `node` and `signal` as the key argument. The `signal`-based lookup does call `get_node`, which means that I do not have to worry about any algorithm using either `node` or `signal` types to access the map.

Furthermore, the `signal`-based lookup is deactivated if the types of `node` and `signal` are identical, which makes sense because the compiler would not like a redeclaration.

I'm using `uint64_t` for both `node` and `signal` in my network implementation, which means that the `signal`-based lookup is not available to me. However, my signals do not point to the node indexes they represent because they store different information. In other words, signal `2` does not necessarily point to node `2`, and so on. This causes the `node`-based lookup in `node_map` to run into out-of-bounds errors.

Is there an easy way to circumvent this very specific problem I'm facing? It would be a pity if my architecture falls apart here...

**Comment by hriener** [comment]
Would it work if you wrap the `uint64_t`s into two different structs (`node` and `signal`). Then you also have the advantage of compile-time type-safety and the compiler will produce errors when you confuse `node` with `signal` and vice versa.

**Comment by marcelwa** [comment]
I tried this first actually, but it gave me compile errors because there was no known conversion from `signal` to `mockturtle::node_pointer<0>` then.

**Comment by hriener** [comment]
Could you give me more details on your node and signal type and also on how your storage looks like?
A minimal example that I can use to reproduce the problem would help.

I assume that you are trying something like this:
```c++
#include <mockturtle/networks/storage.hpp>
#include <mockturtle/utils/node_map.hpp>

namespace mockturtle
{

template<class Node>
struct gate_hash
{
  uint64_t operator()( Node const& n ) const
  {
    uint64_t seed = -2011;
    seed += n.children[0].index * 7937;
    seed += n.children[1].index * 2971;
    return seed;
  }
};

using gate_storage = storage<regular_node<2, 0, 0>,
                             empty_storage_data,
                             gate_hash<regular_node<2, 0, 0>>>;

class gate_network
{
public:
  static constexpr auto min_fanin_size = 2u;
  static constexpr auto max_fanin_size = 2u;

  using base_type = gate_network;
  using storage = std::shared_ptr<gate_storage>;
  using node = uint64_t;

  struct signal
  {
    signal() = default;
    
    explicit signal( uint64_t value )
      : value( value )
    {}
      
    uint64_t value;
  };

public:
  gate_network()
    : storage_( std::make_shared<gate_storage>() )
  {}
  
  signal get_constant( bool value ) const
  {
    return signal( value );
  }
  
  node get_node( signal const& f ) const
  {
    return f.value;
  }

  auto size() const
  {
    return storage_->nodes.size();
  }

  uint32_t node_to_index( node const& n ) const
  {
    return n;
  }
  
public:
  std::shared_ptr<gate_storage> storage_;
};

} // mockturtle

int main()
{
  namespace mt = mockturtle;
  
  mt::gate_network g;
  assert( g.size() == 1u );
  
  mt::node_map<uint32_t, mt::gate_network> m( g );
  m[g.get_node( g.get_constant( 0 ) )] = 10;
  assert( m[g.get_node( g.get_constant( false ) )] == 10 );
  assert( m[g.get_constant( false)] == 10 );

  return 0;
}
```

**Comment by marcelwa** [comment]
That's not that far off. I circumvented the problem for now by making `node` a `uint32_t` while keeping `signal` at `uint64_t`: https://github.com/marcelwa/fiction/blob/restructure/src/topo/gate_level_layout.hpp#L75 However, that's a rather unsatisfactory solution. When I try to make my `signal` type `coord_t`, which is a struct that uses bitfields of a `uint64_t` and encodes positions (https://github.com/marcelwa/fiction/blob/restructure/src/topo/coordinate.hpp#L15), I get the above-mentioned error that there is no known conversion to `mockturtle::node_pointer<0>`.

**Pull request closed without merging**
