### PR TITLE
LUT mapping

### PR DESCRIPTION
**Pull request by msoeken**
This pull request adds a LUT mapping algorithm to mockturtle which produces equivalent results to `&mf` in case of AIGs, but is implemented in a generic way. In order to represent the mapping in a network, the network interface is extended by the following methods:

- `has_mapping`
- `num_cells`
- `is_cell_root`
- `clear_mapping`
- `add_to_mapping`
- `remove_from_mapping`
- `cell_function`
- `set_cell_function`
- `foreach_cell_fanin`

None of the current network implementations supports any of these methods, but they can be added using the `mapping_view`. A template parameter for that view can configure whether the view implements the two methods `cell_function` and `set_cell_function` to store truth tables associated to a cell. The view implements all other mapping methods.

The cost function of a cut can be configured via the `CutData` type which is passed as template argument to `lut_mapping`. This argument defaults to `cut_enumeration_mf_cut` which implements the cost function of ABC's `&mf`.

### CODE REVIEW

**Comment by msoeken** [comment]
@whaaswijk Last Wednesday we briefly discussed the method names for the mapped network interface. The idea was not to use `lut` in the names. What would be your proposal?

**Comment by msoeken** [comment]
@whaaswijk I updated the interface method names as discussed in the meeting today.

**Comment by msoeken** [comment]
Yes, because the algorithm is performing k-LUT mapping.

**Comment by whaaswijk** [comment]
In that case, it seems fine with me.

**Pull request merged**
