### PR TITLE
Clean up handling of temporary files in test suite

### PR DESCRIPTION
**Pull request by rocallahan**
The current working directory may not be writable so it's better to write files explicitly to `/tmp` and clean them up afterward.

### CODE REVIEW

**Comment by rocallahan** [comment]
I need to work out a Windows-compatible solution here.

**Comment by rocallahan** [comment]
Actually it looks like a lot of tests assume the current working directory is writable, so we should fix this another way.

**Comment by costamag** [comment]
@aletempiac, the coverage report is triggered by the branching added by @rocallahan. Testing all of them requires considering many cases, and from the code we can see that he is giving us a better handling of the files. Do you suggest to address the coverage issue or can we proceed with merging this PR?

**Comment by rocallahan** [comment]
Hmm, the tests pass for me.

**Comment by costamag** [comment]
Dear @rocallahan,this is great, thank you for the tests!

**Pull request merged**
