### PR TITLE
XMG resubstitution considering XOR3 and MAJ resubstitutions.

### PR DESCRIPTION
**Pull request by shubhamrai26**
Resubstitution with Xor3-Majority graphs (X3MG). 
Filtering Rule applied 
Evaluate Cost function for X3MGs implemented in the properties.

### CODE REVIEW

**Comment by hriener** [comment]
Thank you for the PR.
Please without experiments, but quality tests.

**Comment by shubhamrai26** [comment]
Ok, I will do that then. I will add the quality test case later on. 

Do I need to create a new branch with just the xmg_cost file ?  and then cherrypick to push it to this remote branch ? 
or
 I can still do from the present history as well  where I can cherrypick the xmg_cost commit and push it as separate branch and then again issue a pull-request ?

**Comment by hriener** [comment]
Either you start over with a new branch/PR and we close this one or you remove/add files to this branch/PR.
Please also update the documentation accordingly.

**Comment by shubhamrai26** [comment]
Removed the experiments file. 
I guess I should commit them as well but should I create a new branch for them ?

**Comment by hriener** [comment]
I have added functions to kitty to compute the distinguishing power of a truth table in PR https://github.com/msoeken/kitty/pull/84

**Comment by hriener** [comment]
This PR looks pretty good.  However, a quality test is still missing.

**Comment by hriener** [comment]
Thank you!

**Comment by shubhamrai26** [comment]
I dont think this is merged with mockturtle ?  Should I add these functions seperately in mockturtle/lib/kitty ?



________________________________

**Pull request merged**
