### PR TITLE
Update kitty

### PR DESCRIPTION
**Pull request by msoeken**
Waiting for 👍 from @hriener

### CODE REVIEW

**Comment by hriener** [comment]
Still misses the backport.

**Comment by msoeken** [comment]
> Still misses the backport.

Which one?

**Comment by hriener** [comment]
https://github.com/lsils/mockturtle/blob/master/lib/kitty/kitty/cube.hpp#L142

The code will now merge correctly with `master`, but it will break the next time when you copy `kitty` from the other repository.

**Comment by msoeken** [comment]
Backport in https://github.com/msoeken/kitty/pull/100

**Pull request merged**
