### PR TITLE
Wrapper for ABC exorcism

### PR DESCRIPTION
**Pull request by msoeken**

### CODE REVIEW

**Comment by hriener** [comment]
Could we separate this code from `mockturtle`? I would be interested in trying `exorcism` in `angel`.

**Comment by msoeken** [comment]
I will add [this version of exorcism](github.com/boschmitt/exorcism) instead. That one is already separated. But if you are interested in having the original exorcism, I can make a Github project just with the extracted ABC code.

**Comment by hriener** [comment]
Can we have both? If I recall correctly Bruno's version is limited to exorlink-3 at most. Not sure if this issue has been resolved.

**Comment by msoeken** [comment]
The source code indicates to also have exorlink-4, but we can have both. So I separate the source for the ABC exorcism version to an lsils repository. The exorcism of Bruno is already separate, but it could be merged into easy. Then we copy files (or submodules) to both mockturtle and angel.

**Comment by hriener** [comment]
Agreed. There are other things that I want to re-integrate into `easy` anyway; then, I can also add Bruno's `exorcism`.

**Comment by msoeken** [comment]
Extracted the files to https://github.com/lsils/exorcism and kept a copy inside mockturtle.

**Pull request merged**
