### PR TITLE
Fix create_po not properly passing through assigned names

### PR DESCRIPTION
**Pull request by marcelwa**
`depth_view` does not properly pass through assigned PO names. Consequently, calling the function `create_po( f, name )` on some `mockturtle::names_view<mockturtle::depth_view<Ntk>>` fails.

This fix addresses the issue by adding the `std::string const& name = std::string()` parameter in accordance with `mockturtle`'s API specification.

### CODE REVIEW

**Comment by hriener** [comment]
Do you use this feature actively? There is a proposal on removing names from `create_pi` and `create_po`.

**Comment by marcelwa** [comment]
Yes, I'm using this feature. How would your adjustments look like? Do you plan to keep `names_view` as is and remove the names everywhere else?

**Comment by hriener** [comment]
Yes.

**Comment by marcelwa** [comment]
I'm probably fine with that. Until then, this adjustment would keep me going. Maybe it's a valuable saving point for other people, too, to come back to or cherry-pick from in the future.

**Comment by lee30sonia** [comment]
This will be resolved with #559, so I'm closing it (finally!).

**Pull request closed without merging**
