### PR TITLE
Sequential circuit

### LINKED ISSUE #572: Write a sequential circuit with register outputs.
**Describe the bug**
A register output (RO) created before a primary output (PO) will become a PO when writing to the BLIF file. (because `write_blif` always assume the first `num_co` index are POs and the rest are ROs).

**To Reproduce**
```c
  sequential<klut_network> klut;

  const auto a = klut.create_pi();
  const auto b = klut.create_pi();
  const auto f1 = klut.create_or( a, b );

  klut.create_ri( f1 );
  const auto f2 = klut.create_ro(); // always_ff: f2 <= f1;

  klut.create_po( f2 );

  write_blif( klut, "<filename>.blif" );
```

**Environment**
 - OS: Linux
 - Compiler: GCC 12
 - Compilation mode: DEBUG and RELEASE

**Additional context**
In the current version (commit 39fd19c3215da2d395c769cfa92df578847ae6f7), ROs and POs are mixed in all network implementations.

**Check list**
 * [x] I have tried to run in DEBUG mode and there was no assertion failure (or the reported bug is an assertion failure).
 * [x] I have made sure that the provided code compiles and the testcase reproduces the error.
 * [x] I have minimized the testcase.

### PR DESCRIPTION
**Pull request by Nozidoali**
- fix BLIF reader/write BLIF for sequential circuits  
- consider sequential logic during cut enumeration and when collapsing mapped network 
- close #572

### CODE REVIEW

**Comment by Nozidoali** [comment]
Ready to merge if all tasks below are checked :))

- [ ] fix `write_blif`
- [ ] add test cases for `write_blif` that the previous implementation would fail.
- [ ] add test cases for `name_view`ed BLIF read/write

**Comment by lee30sonia** [comment]
Thank you for the contribution. A few things:
- Updates to `lorina` should be made in the source repository first. It would also be great to provide a test case there to justify your fix.
- Changes to network interfaces should be documented.
- Would also be nice to have a test to ensure correctness of sequential cuts.

**Comment by Nozidoali** [comment]
Todo:

- [ ] remove unnecessary modifications
- [ ] update changes to the interface in the documentation 
- [ ] add test cases for sequential k-LUT mapping

**Comment by lee30sonia** [comment]
Thanks!

**Pull request merged**
