### PR TITLE
Circuit validator

### PR DESCRIPTION
**Pull request by lee30sonia**
Validates potential circuit optimization choices with SAT by checking functional equivalence to the root node. 
Supports dependency functions of more than one gate.
Supports AND2, XOR2, XOR3, MAJ.
Supports CEX randomization.
Supports ODC consideration.
Not yet supported: incremental CNF construction.

### CODE REVIEW

**Comment by lee30sonia** [comment]
Hmm I think checks are failing because of Z3.

**Comment by hriener** [comment]
Thank you for this contribution. The PR looks very good.

Here are a few minor comments:
- The changes to `bill` (`bookmark`, `rollback`, `set_random_phase`) should be contributed back to `bill` via PR. I believe that the names `push` and `pop` are more common and intuitive for `bookmark` and `rollback`.
- Some of the static_asserts in `circuit_validator` are disabled.
- The `circuit_validator` should be mentioned in the documentation and changelog of `mockturtle`.
- Is there a particular reason for not supporting `validate` with a signal argument? This may simplify some of the test cases.

**Comment by hriener** [comment]
Looks good to me. Is it ready to be merged?

The class `circuit_validator` should be also mentioned in `mockturtle`'s documentation and changelog. However, it can be also added afterward.

**Comment by lee30sonia** [comment]
> Looks good to me. Is it ready to be merged?
> 
> The class `circuit_validator` should be also mentioned in `mockturtle`'s documentation and changelog. However, it can be also added afterward.

I am working on the documentation.

**Comment by lee30sonia** [comment]
Documentation is committed, but I'm not sure if the syntax is all good...

**Comment by hriener** [comment]
> Documentation is committed, but I'm not sure if the syntax is all good...

If you run `make html` in your docs directory, the Makefile will locally generate the documentation on your computer in a directory called `docs/build`. You can then check if the markup looks correct.

**Pull request merged**
