### PR TITLE
Functional reduction

### PR DESCRIPTION
**Pull request by lee30sonia**
Detect and substitute constant nodes and functionally equivalent nodes. Supports AIG, MIG, XAG, XMG.
Also updated `bill` and `kitty`.

### CODE REVIEW

**Comment by lee30sonia** [comment]
still missing: documentation and unit test.

**Comment by lee30sonia** [comment]
Ready to be merged!

**Comment by lee30sonia** [comment]
Now it's really ready!

**Comment by hriener** [comment]
Thanks!

**Pull request merged**
