### PR TITLE
Add dedicated operator== overload between signal and pointer_type

### PR DESCRIPTION
**Pull request by b1f6c1c4**
C++20 has significant modifications on the overloads of `operator==`. See the following demo: https://godbolt.org/z/dTvncj

In order to ease the transition to C++20 some day, it'd be better to stop relying on the C++17's `operator==` behavior; otherwise, the following error would occur when compiling the existing code base using C++20:

```
../test/networks/xag.cpp:264:19: error: ambiguous overload for ‘operator==’ (operand types are ‘const mockturtle::node_pointer<1>’ and ‘const mockturtle::xag_network::signal’)
  264 |       CHECK( node == f1 ); /* first po */
```

### CODE REVIEW

**Comment by b1f6c1c4** [comment]
Besides, it would be better to add another item(s) into `.github/workflows/*.yml` that verifies C++20-compliance of the source code. It may not be necessary to change the global `CMakeList.txt` to C++20 at this moment, IMO.

**Comment by hriener** [comment]
Thank you for the PR!

As you have noticed, we do not support C++20 yet. However, I appreciate the changes to prepare `mockturtle` for the future.

Do you have a suggestion for the workflow update? What's the compiler that you would like to target?

**Comment by b1f6c1c4** [comment]
@hriener I believe GCC >=10.2.0 would do the job (I'm personally using 10.2.0 locally.)
Besides, I think passing some parameters to the `cmake` command line in somewhere like https://github.com/lsils/mockturtle/blob/master/.github/workflows/linux.yml#L24 would be beneficial.

**Comment by hriener** [comment]
Agreed. I'm happy to merge the workflow/CMake update if you would like to commit the changes to the branch (assuming that the required changes are not too invasive).

**Comment by b1f6c1c4** [comment]
I'm not very familiar with github workflows so maybe you could merge the PR first and the modify `.github/workflows/*.yml` later.

**Comment by hriener** [comment]
I like your idea of adding a c++20 compiler first to verify that the changes are indeed required and correct. Also, updating the workflows should be not too complicated; let me see if I can get it done by the end of the week.

**Comment by hriener** [comment]
Thanks!

**Pull request merged**
