### PR TITLE
Declare mockturtle as a SYSTEM library in CMake

### PR DESCRIPTION
**Pull request by marcelwa**
Libraries declared as `SYSTEM` do not propagate compiler warnings to top-level projects. Thereby, when using `mockturtle` as a library while having a stricter compiler warnings setup, this suppresses warnings originating in `mockturtle`. Since the test cases now link `PUBLIC`ly, you are still able to see all warnings as before while working on `mockturtle`. The changes only affect people including it.

For more information see, e.g., https://foonathan.net/2018/10/cmake-warnings/

A nice compiler warnings setup can be found in Jason Turner's *CPP Starter Project* here: https://github.com/lefticus/cpp_starter_project/blob/master/cmake/CompilerWarnings.cmake

### CODE REVIEW

**Comment by hriener** [comment]
I am wondering what prevents you from declaring `mockturtle` as a `SYSTEM` library on your side, e.g., as in #432. Do you directly include the `CMakeLists.txt` of `mockturtle` in your build process?

**Comment by marcelwa** [comment]
I am by no means an expert in CMake, so I just used `add_subdirectory(mockturtle)`. Issue #432 refers to `autotools` and does not really help me, unfortunately. If you can point me towards a client-side solution, I'd be more than happy to give it a try.

**Comment by hriener** [comment]
Instead of adding the subdirectory, you could just add your own target for `mockturtle` and declare it as `SYSTEM`.

However, your request sounds reasonable. I would suggest adding `PUBLIC` to the `mockturtle`'s examples and experiments too because they are often used as drivers during development.

**Comment by marcelwa** [comment]
If I'm not mistaken, they link `PUBLIC`ly already.

Examples: https://github.com/lsils/mockturtle/blob/7d0f35535d934f98db64e30f69e4cfa880d82ed4/examples/CMakeLists.txt#L6

Experiments: https://github.com/lsils/mockturtle/blob/7d0f35535d934f98db64e30f69e4cfa880d82ed4/experiments/CMakeLists.txt#L30

**Comment by hriener** [comment]
Perfect! Thank you.

**Pull request merged**
