### PR TITLE
Fix failing Windows build

### PR DESCRIPTION
**Pull request by marcelwa**
Trying to compile with different toolsets under Windows reveals compilation errors. I will open a separate issue pointing to this PR.

### CODE REVIEW

**Comment by marcelwa** [comment]
As mentioned in #531, this PR fixes a couple of compilation errors on Windows. If you want, you could merge this PR now. Do you want me to revert the changes I made to your Windows CI? They were only intended to showcase the problem.

**Comment by lee30sonia** [comment]
Are these toolsets commonly-used ones? If so, I think we can keep them.

**Comment by marcelwa** [comment]
I believe `v142` is the default in Visual Studio 2019. I thought it would be beneficial to additionally test with Clang via the `ClangCL` toolset.

**Comment by lee30sonia** [comment]
Looks good to me. Could you please resolve the conflict (keeping yours) so that I can merge it? Thanks!

**Comment by lee30sonia** [comment]
@aletempiac FYI since your code is affected

**Pull request merged**
