### PR TITLE
Fix XAG constant fanin optimization

### PR DESCRIPTION
**Pull request by boschmitt**
This does two things:

1. Fix a bug in the XAG constant fanin optimisation routine. 
2. Substitute a hand rolled symmetric difference algorithm for the standard one.

NOTE: It still misses a test case capable of preventing this bug from reappearing.

### CODE REVIEW

**Comment by hriener** [comment]
Thank you for the bugfix.

A failing test case would be very useful.

**Comment by boschmitt** [comment]
Giulia is looking into it. I couldn't managed to produce a simple on by hand. Unfortunately, I don't have much time right now to look deeper into it, but this fixes the problem we were having. 

I think we can merge it and create an Issue to remember getting back to creating a failing test case.

**Comment by hriener** [comment]
What kind of bug is fixed by this PR? A segmentation fault?

**Comment by boschmitt** [comment]
> A segmentation fault?

Yes

**Comment by hriener** [comment]
I added a failing test case. The problem should be solved.

Thanks for your contribution!

**Pull request merged**
