### PR TITLE
Code simplifications and additional functionality for kLUT network

### PR DESCRIPTION
**Pull request by marcelwa**
This PR provides some code simplifications in `klut_network`'s member functions `is_ci`, `is_pi`, and `is_ro`. Additionally, functions for checking nodes against logic primitives were added in accordance with `mockturtle`'s API specification. The additions are covered by a test case.

### CODE REVIEW

**Comment by marcelwa** [comment]
It seems like the failing build is missing the `clang++-9` dependency. It can be installed via `sudo apt-get install clang-9`.

**Comment by hriener** [comment]
The `is_XXX` methods are used to check structural properties and not functional properties. For example, in a `xag_network`, the methods `is_and` and `is_xor` can return true, but all other `is_XXX` methods will return false (because the network is constructed only from AND and XOR gates). Although it's possible to construct, e.g., the OR function within a `xag_network`, the `is_or` method will always evaluate to false. In a `klut_network`, there is a method called `is_function` to check if a node is a general function (or LUT) node.

**Comment by marcelwa** [comment]
Thank you for reaching back. I understand that these implementations do not match the intended behavior. I've removed the `is_XXX` functions again while keeping the other changes. The `create_nand` function for instance is required by the `verilog_reader`. If the additions are helpful for you, feel free to merge them. Otherwise, I'd be okay with you closing the PR.

**Comment by hriener** [comment]
The other changes are good and we will, of course, merge them! Thanks for your help in improving the API.

**Comment by hriener** [comment]
Can you merge master into your branch?

**Pull request merged**
