### PR TITLE
klut to AIG/XAG/MIG

### PR DESCRIPTION
**Pull request by costamag**
Work done:
1. resynthesis function combining Disjoint Support Decomposition, shannon decomposition and NPN-based resynthesis.
takes as input a k-LUT and returns a AIG, XAG or MIG network.
2. tests considering 4 cases for the three networks:
    case 1: the function is fully DS-decomposable;
    case 2: one step of DSD and then the NPN mapping is performed;
    case 3: No DSD. One step of shannon and then NPN mapping;
    case 4: One step of DSD, one of Shannon and then NPN mapping.

### CODE REVIEW

**Comment by lee30sonia** [comment]
(Just to clarify) After resolving all the comments, please let me know (explicitly) that I should review it again; otherwise I will take it as still work-in-progress.

**Comment by costamag** [comment]
Dear Sonia,
Sorry, I thought I had told you that I had re-submitted it some days ago but I was not sure about having done the documentation properly. Did you sent me other comments?
All the best,
Andrea

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 30 Ott 2021, 00:05, Siang-Yun (Sonia) Lee ha scritto:

**Comment by lee30sonia** [comment]
I saw there are some unresolved comments above so I thought you haven't completely finished. But now I see, they are outdated. Okay, I'll review again later.

**Comment by costamag** [comment]
I see, in the future I will resolve the comments explicitly. Thank you for pointing this out.
All the best,
Andrea

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 30 Ott 2021, 08:25, Siang-Yun (Sonia) Lee ha scritto:

**Review by lee30sonia — APPROVED** [review]

**Comment by lee30sonia** [comment]
To speed-up the process, I fixed a few things directly by myself:
- I moved the file out of the `node_resynthesis` directory, because it does not implement a new resynthesis method, but a wrapper to be used by higher-levle users.
- Updates in the documentation: Some are simply writing/wording style, some are syntax issues (e.g. the `:math:` decoration, `tparam` for template parameters, insert an empty line to change line, etc.), and also some to enhance understandability for outside users and to reduce repetitions.
- Fixed inclusion style: Within `mockturtle`, we should use `#include "<relative_path>.hpp"`. When including with `#include <mockturtle/<some_algorithm>.hpp`, we are using `mockturtle` as a system-level library. (See, e.g., [here](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename))
- I don't understand why you need the `always_false<T>` template class.
- I removed the parameter and statistics objects, because I suppose this function will be used by users who just wants to quickly and easily convert the network and would not be interested in making it verbose or seeing the stats. This also simplifies the interface.
- Finally, I ran `clang-format -i <file>` to automatically correct spaces, intentations, etc.

**Comment by lee30sonia** [comment]
@costamag if you are fine with all the changes, we can merge the PR.

**Comment by costamag** [comment]
dear @lee30sonia, everything is fine for me. Yesterday evening I saw that a typo in a header was giving troubles to the checks but if it is fixed I thank you for the adjustments and for the suggestions and I am fine for the merging.

**Pull request merged**
